apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sachin-hello-world-app
  annotations:
    github.com/project-slug: sachinkhisti/sachin-hello-world-app
    backstage.io/techdocs-ref: value
spec:
  type: website
  lifecycle: hello-world Experience
  owner: sachin.khisti@wolterskluwer.com
relations:
  - type: memberOf
    target: component:hello-world
  
